# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: services/agent/v0/agent.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import services.agent.v0.agent_pb2


class AgentBase(abc.ABC):

    @abc.abstractmethod
    async def GetAgentInformation(self, stream: 'grpclib.server.Stream[services.agent.v0.agent_pb2.AgentInformationRequest, services.agent.v0.agent_pb2.AgentInformation]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/services.agent.v0.Agent/GetAgentInformation': grpclib.const.Handler(
                self.GetAgentInformation,
                grpclib.const.Cardinality.UNARY_UNARY,
                services.agent.v0.agent_pb2.AgentInformationRequest,
                services.agent.v0.agent_pb2.AgentInformation,
            ),
        }


class AgentStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetAgentInformation = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.agent.v0.Agent/GetAgentInformation',
            services.agent.v0.agent_pb2.AgentInformationRequest,
            services.agent.v0.agent_pb2.AgentInformation,
        )
