# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: services/builder/v0/builder.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import base.v0.service_pb2
import base.v0.network_pb2
import base.v0.endpoint_pb2
import base.v0.environment_pb2
import base.v0.configuration_pb2
import services.agent.v0.communicate_pb2
import services.builder.v0.docker_pb2
import services.builder.v0.deployment_pb2
import services.builder.v0.builder_pb2


class BuilderBase(abc.ABC):

    @abc.abstractmethod
    async def Load(self, stream: 'grpclib.server.Stream[services.builder.v0.builder_pb2.LoadRequest, services.builder.v0.builder_pb2.LoadResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Init(self, stream: 'grpclib.server.Stream[services.builder.v0.builder_pb2.InitRequest, services.builder.v0.builder_pb2.InitResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Create(self, stream: 'grpclib.server.Stream[services.builder.v0.builder_pb2.CreateRequest, services.builder.v0.builder_pb2.CreateResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Update(self, stream: 'grpclib.server.Stream[services.builder.v0.builder_pb2.UpdateRequest, services.builder.v0.builder_pb2.UpdateResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Sync(self, stream: 'grpclib.server.Stream[services.builder.v0.builder_pb2.SyncRequest, services.builder.v0.builder_pb2.SyncResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Build(self, stream: 'grpclib.server.Stream[services.builder.v0.builder_pb2.BuildRequest, services.builder.v0.builder_pb2.BuildResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Deploy(self, stream: 'grpclib.server.Stream[services.builder.v0.builder_pb2.DeploymentRequest, services.builder.v0.builder_pb2.DeploymentResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Communicate(self, stream: 'grpclib.server.Stream[services.agent.v0.communicate_pb2.Engage, services.agent.v0.communicate_pb2.InformationRequest]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/services.builder.v0.Builder/Load': grpclib.const.Handler(
                self.Load,
                grpclib.const.Cardinality.UNARY_UNARY,
                services.builder.v0.builder_pb2.LoadRequest,
                services.builder.v0.builder_pb2.LoadResponse,
            ),
            '/services.builder.v0.Builder/Init': grpclib.const.Handler(
                self.Init,
                grpclib.const.Cardinality.UNARY_UNARY,
                services.builder.v0.builder_pb2.InitRequest,
                services.builder.v0.builder_pb2.InitResponse,
            ),
            '/services.builder.v0.Builder/Create': grpclib.const.Handler(
                self.Create,
                grpclib.const.Cardinality.UNARY_UNARY,
                services.builder.v0.builder_pb2.CreateRequest,
                services.builder.v0.builder_pb2.CreateResponse,
            ),
            '/services.builder.v0.Builder/Update': grpclib.const.Handler(
                self.Update,
                grpclib.const.Cardinality.UNARY_UNARY,
                services.builder.v0.builder_pb2.UpdateRequest,
                services.builder.v0.builder_pb2.UpdateResponse,
            ),
            '/services.builder.v0.Builder/Sync': grpclib.const.Handler(
                self.Sync,
                grpclib.const.Cardinality.UNARY_UNARY,
                services.builder.v0.builder_pb2.SyncRequest,
                services.builder.v0.builder_pb2.SyncResponse,
            ),
            '/services.builder.v0.Builder/Build': grpclib.const.Handler(
                self.Build,
                grpclib.const.Cardinality.UNARY_UNARY,
                services.builder.v0.builder_pb2.BuildRequest,
                services.builder.v0.builder_pb2.BuildResponse,
            ),
            '/services.builder.v0.Builder/Deploy': grpclib.const.Handler(
                self.Deploy,
                grpclib.const.Cardinality.UNARY_UNARY,
                services.builder.v0.builder_pb2.DeploymentRequest,
                services.builder.v0.builder_pb2.DeploymentResponse,
            ),
            '/services.builder.v0.Builder/Communicate': grpclib.const.Handler(
                self.Communicate,
                grpclib.const.Cardinality.UNARY_UNARY,
                services.agent.v0.communicate_pb2.Engage,
                services.agent.v0.communicate_pb2.InformationRequest,
            ),
        }


class BuilderStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Load = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.builder.v0.Builder/Load',
            services.builder.v0.builder_pb2.LoadRequest,
            services.builder.v0.builder_pb2.LoadResponse,
        )
        self.Init = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.builder.v0.Builder/Init',
            services.builder.v0.builder_pb2.InitRequest,
            services.builder.v0.builder_pb2.InitResponse,
        )
        self.Create = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.builder.v0.Builder/Create',
            services.builder.v0.builder_pb2.CreateRequest,
            services.builder.v0.builder_pb2.CreateResponse,
        )
        self.Update = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.builder.v0.Builder/Update',
            services.builder.v0.builder_pb2.UpdateRequest,
            services.builder.v0.builder_pb2.UpdateResponse,
        )
        self.Sync = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.builder.v0.Builder/Sync',
            services.builder.v0.builder_pb2.SyncRequest,
            services.builder.v0.builder_pb2.SyncResponse,
        )
        self.Build = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.builder.v0.Builder/Build',
            services.builder.v0.builder_pb2.BuildRequest,
            services.builder.v0.builder_pb2.BuildResponse,
        )
        self.Deploy = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.builder.v0.Builder/Deploy',
            services.builder.v0.builder_pb2.DeploymentRequest,
            services.builder.v0.builder_pb2.DeploymentResponse,
        )
        self.Communicate = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.builder.v0.Builder/Communicate',
            services.agent.v0.communicate_pb2.Engage,
            services.agent.v0.communicate_pb2.InformationRequest,
        )
