apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: python-visitors-backend
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      name: http-port
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: grpc-port
      port: 9090
      targetPort: 9090
