# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base/v0/project.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from base.v0 import application_pb2 as base_dot_v0_dot_application__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x61se/v0/project.proto\x12\x07\x62\x61se.v0\x1a\x1b\x62uf/validate/validate.proto\x1a\x19\x62\x61se/v0/application.proto\"\x99\x01\n\x07Project\x12\x32\n\x04name\x18\x01 \x01(\tB\x1e\xbaH\x1br\x19\x10\x03\x18\x19\x32\x0c^[a-z0-9-]+$h\x01\xba\x01\x02--R\x04name\x12 \n\x0b\x64\x65scription\x18\x02 \x01(\tR\x0b\x64\x65scription\x12\x38\n\x0c\x61pplications\x18\x03 \x03(\x0b\x32\x14.base.v0.ApplicationR\x0c\x61pplications\"\xac\x01\n\x0eManagedProject\x12;\n\x0forganization_id\x18\x01 \x01(\tB\x12\xbaH\x0fr\r2\x0b^[a-z]{10}$R\x0eorganizationId\x12\x31\n\nproject_id\x18\x02 \x01(\tB\x12\xbaH\x0fr\r2\x0b^[a-z]{10}$R\tprojectId\x12*\n\x07project\x18\x03 \x01(\x0b\x32\x10.base.v0.ProjectR\x07projectB\x8a\x01\n\x0b\x63om.base.v0B\x0cProjectProtoP\x01Z0github.com/codefly-dev/core/generated/go/base/v0\xa2\x02\x03\x42VX\xaa\x02\x07\x42\x61se.V0\xca\x02\x07\x42\x61se\\V0\xe2\x02\x13\x42\x61se\\V0\\GPBMetadata\xea\x02\x08\x42\x61se::V0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base.v0.project_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.base.v0B\014ProjectProtoP\001Z0github.com/codefly-dev/core/generated/go/base/v0\242\002\003BVX\252\002\007Base.V0\312\002\007Base\\V0\342\002\023Base\\V0\\GPBMetadata\352\002\010Base::V0'
  _globals['_PROJECT'].fields_by_name['name']._options = None
  _globals['_PROJECT'].fields_by_name['name']._serialized_options = b'\272H\033r\031\020\003\030\0312\014^[a-z0-9-]+$h\001\272\001\002--'
  _globals['_MANAGEDPROJECT'].fields_by_name['organization_id']._options = None
  _globals['_MANAGEDPROJECT'].fields_by_name['organization_id']._serialized_options = b'\272H\017r\r2\013^[a-z]{10}$'
  _globals['_MANAGEDPROJECT'].fields_by_name['project_id']._options = None
  _globals['_MANAGEDPROJECT'].fields_by_name['project_id']._serialized_options = b'\272H\017r\r2\013^[a-z]{10}$'
  _globals['_PROJECT']._serialized_start=91
  _globals['_PROJECT']._serialized_end=244
  _globals['_MANAGEDPROJECT']._serialized_start=247
  _globals['_MANAGEDPROJECT']._serialized_end=419
# @@protoc_insertion_point(module_scope)
