apiVersion: v1
kind: Secret
metadata:
  name: secret-server
  namespace: "python-visitors-backend"
data:
  CODEFLY_PROVIDER__BACKEND__CACHE___REDIS____READ: cmVkaXM6Ly9yZWFkLWNhY2hlLnB5dGhvbi12aXNpdG9ycy1iYWNrZW5kLnN2Yy5jbHVzdGVyLmxvY2FsOjcwNzA=
  CODEFLY_PROVIDER__BACKEND__CACHE___REDIS____WRITE: cmVkaXM6Ly93cml0ZS1jYWNoZS5weXRob24tdmlzaXRvcnMtYmFja2VuZC5zdmMuY2x1c3Rlci5sb2NhbDo3MDcw
  CODEFLY_PROVIDER__BACKEND__STORE___POSTGRES____CONNECTION: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAaG9zdC5kb2NrZXIuaW50ZXJuYWw6NDIzNTAvdmlzaXRvcnM/c3NsbW9kZT1kaXNhYmxl
