apiVersion: v1
kind: Secret
metadata:
  name: secret-store
  namespace: "python-visitors-backend"
data:
    CODEFLY_PROVIDER__BACKEND__STORE___POSTGRES____CONNECTION: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAaG9zdC5kb2NrZXIuaW50ZXJuYWw6NDIzNTAvdmlzaXRvcnM/c3NsbW9kZT1kaXNhYmxl
