# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: services/runtime/v0/runtime.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import base.v0.scope_pb2
import base.v0.spec_pb2
import base.v0.environment_pb2
import base.v0.service_pb2
import base.v0.endpoint_pb2
import base.v0.network_pb2
import base.v0.configuration_pb2
import services.agent.v0.agent_pb2
import services.agent.v0.communicate_pb2
import services.runtime.v0.runtime_pb2


class RuntimeBase(abc.ABC):

    @abc.abstractmethod
    async def Load(self, stream: 'grpclib.server.Stream[services.runtime.v0.runtime_pb2.LoadRequest, services.runtime.v0.runtime_pb2.LoadResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Init(self, stream: 'grpclib.server.Stream[services.runtime.v0.runtime_pb2.InitRequest, services.runtime.v0.runtime_pb2.InitResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Start(self, stream: 'grpclib.server.Stream[services.runtime.v0.runtime_pb2.StartRequest, services.runtime.v0.runtime_pb2.StartResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Stop(self, stream: 'grpclib.server.Stream[services.runtime.v0.runtime_pb2.StopRequest, services.runtime.v0.runtime_pb2.StopResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Information(self, stream: 'grpclib.server.Stream[services.runtime.v0.runtime_pb2.InformationRequest, services.runtime.v0.runtime_pb2.InformationResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Communicate(self, stream: 'grpclib.server.Stream[services.agent.v0.communicate_pb2.Engage, services.agent.v0.communicate_pb2.InformationRequest]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/services.runtime.v0.Runtime/Load': grpclib.const.Handler(
                self.Load,
                grpclib.const.Cardinality.UNARY_UNARY,
                services.runtime.v0.runtime_pb2.LoadRequest,
                services.runtime.v0.runtime_pb2.LoadResponse,
            ),
            '/services.runtime.v0.Runtime/Init': grpclib.const.Handler(
                self.Init,
                grpclib.const.Cardinality.UNARY_UNARY,
                services.runtime.v0.runtime_pb2.InitRequest,
                services.runtime.v0.runtime_pb2.InitResponse,
            ),
            '/services.runtime.v0.Runtime/Start': grpclib.const.Handler(
                self.Start,
                grpclib.const.Cardinality.UNARY_UNARY,
                services.runtime.v0.runtime_pb2.StartRequest,
                services.runtime.v0.runtime_pb2.StartResponse,
            ),
            '/services.runtime.v0.Runtime/Stop': grpclib.const.Handler(
                self.Stop,
                grpclib.const.Cardinality.UNARY_UNARY,
                services.runtime.v0.runtime_pb2.StopRequest,
                services.runtime.v0.runtime_pb2.StopResponse,
            ),
            '/services.runtime.v0.Runtime/Information': grpclib.const.Handler(
                self.Information,
                grpclib.const.Cardinality.UNARY_UNARY,
                services.runtime.v0.runtime_pb2.InformationRequest,
                services.runtime.v0.runtime_pb2.InformationResponse,
            ),
            '/services.runtime.v0.Runtime/Communicate': grpclib.const.Handler(
                self.Communicate,
                grpclib.const.Cardinality.UNARY_UNARY,
                services.agent.v0.communicate_pb2.Engage,
                services.agent.v0.communicate_pb2.InformationRequest,
            ),
        }


class RuntimeStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Load = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.runtime.v0.Runtime/Load',
            services.runtime.v0.runtime_pb2.LoadRequest,
            services.runtime.v0.runtime_pb2.LoadResponse,
        )
        self.Init = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.runtime.v0.Runtime/Init',
            services.runtime.v0.runtime_pb2.InitRequest,
            services.runtime.v0.runtime_pb2.InitResponse,
        )
        self.Start = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.runtime.v0.Runtime/Start',
            services.runtime.v0.runtime_pb2.StartRequest,
            services.runtime.v0.runtime_pb2.StartResponse,
        )
        self.Stop = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.runtime.v0.Runtime/Stop',
            services.runtime.v0.runtime_pb2.StopRequest,
            services.runtime.v0.runtime_pb2.StopResponse,
        )
        self.Information = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.runtime.v0.Runtime/Information',
            services.runtime.v0.runtime_pb2.InformationRequest,
            services.runtime.v0.runtime_pb2.InformationResponse,
        )
        self.Communicate = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.runtime.v0.Runtime/Communicate',
            services.agent.v0.communicate_pb2.Engage,
            services.agent.v0.communicate_pb2.InformationRequest,
        )
