apiVersion: v1
kind: ConfigMap
metadata:
  name: config-frontend
  namespace: "python-visitors-web"
data:
  CODEFLY__ENDPOINT__BACKEND__SERVER__REST__REST: http://server.python-visitors-backend.svc.cluster.local:8080
  CODEFLY__REST_ROUTE__BACKEND__SERVER__REST__REST___VERSION___GET: application
  CODEFLY__REST_ROUTE__BACKEND__SERVER__REST__REST___VISIT__STATISTICS___GET: application
  CODEFLY__REST_ROUTE__BACKEND__SERVER__REST__REST___VISIT___POST: application
