apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: "python-visitors-web-localkube"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: image:tag
          envFrom:
            - configMapRef:
                name: config-frontend
            - secretRef:
                name: secret-frontend
