# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actions/v0/service.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from base.v0 import agent_pb2 as base_dot_v0_dot_agent__pb2
from base.v0 import endpoint_pb2 as base_dot_v0_dot_endpoint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61\x63tions/v0/service.proto\x12\nactions.v0\x1a\x1b\x62uf/validate/validate.proto\x1a\x13\x62\x61se/v0/agent.proto\x1a\x16\x62\x61se/v0/endpoint.proto\"\xf5\x01\n\nAddService\x12\x12\n\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1a\n\x08override\x18\x02 \x01(\x08R\x08override\x12\x1d\n\x04name\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18\x32R\x04name\x12 \n\x0b\x64\x65scription\x18\x04 \x01(\tR\x0b\x64\x65scription\x12\x32\n\x10\x61pplication_path\x18\x05 \x01(\tB\x07\xbaH\x04r\x02\x10\x03R\x0f\x61pplicationPath\x12$\n\x05\x61gent\x18\x06 \x01(\x0b\x32\x0e.base.v0.AgentR\x05\x61gent\x12\x1c\n\tnamespace\x18\x07 \x01(\tR\tnamespace\"\xc0\x01\n\x10SetServiceActive\x12\x12\n\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1d\n\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18\x32R\x04name\x12+\n\x0b\x61pplication\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18\x32R\x0b\x61pplication\x12#\n\x07project\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18\x32R\x07project\x12\'\n\tworkspace\x18\x05 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18\x32R\tworkspace\"\xb6\x02\n\x14\x41\x64\x64ServiceDependency\x12\x12\n\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1d\n\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18\x32R\x04name\x12+\n\x0b\x61pplication\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18\x32R\x0b\x61pplication\x12\x32\n\x0f\x64\x65pendency_name\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18\x32R\x0e\x64\x65pendencyName\x12@\n\x16\x64\x65pendency_application\x18\x05 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18\x32R\x15\x64\x65pendencyApplication\x12*\n\x0cproject_path\x18\x06 \x01(\tB\x07\xbaH\x04r\x02\x10\x03R\x0bprojectPath\x12\x1c\n\tendpoints\x18\x07 \x03(\tR\tendpointsB\x9c\x01\n\x0e\x63om.actions.v0B\x0cServiceProtoP\x01Z3github.com/codefly-dev/core/generated/go/actions/v0\xa2\x02\x03\x41VX\xaa\x02\nActions.V0\xca\x02\nActions\\V0\xe2\x02\x16\x41\x63tions\\V0\\GPBMetadata\xea\x02\x0b\x41\x63tions::V0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'actions.v0.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.actions.v0B\014ServiceProtoP\001Z3github.com/codefly-dev/core/generated/go/actions/v0\242\002\003AVX\252\002\nActions.V0\312\002\nActions\\V0\342\002\026Actions\\V0\\GPBMetadata\352\002\013Actions::V0'
  _globals['_ADDSERVICE'].fields_by_name['name']._options = None
  _globals['_ADDSERVICE'].fields_by_name['name']._serialized_options = b'\272H\006r\004\020\003\0302'
  _globals['_ADDSERVICE'].fields_by_name['application_path']._options = None
  _globals['_ADDSERVICE'].fields_by_name['application_path']._serialized_options = b'\272H\004r\002\020\003'
  _globals['_SETSERVICEACTIVE'].fields_by_name['name']._options = None
  _globals['_SETSERVICEACTIVE'].fields_by_name['name']._serialized_options = b'\272H\006r\004\020\003\0302'
  _globals['_SETSERVICEACTIVE'].fields_by_name['application']._options = None
  _globals['_SETSERVICEACTIVE'].fields_by_name['application']._serialized_options = b'\272H\006r\004\020\003\0302'
  _globals['_SETSERVICEACTIVE'].fields_by_name['project']._options = None
  _globals['_SETSERVICEACTIVE'].fields_by_name['project']._serialized_options = b'\272H\006r\004\020\003\0302'
  _globals['_SETSERVICEACTIVE'].fields_by_name['workspace']._options = None
  _globals['_SETSERVICEACTIVE'].fields_by_name['workspace']._serialized_options = b'\272H\006r\004\020\003\0302'
  _globals['_ADDSERVICEDEPENDENCY'].fields_by_name['name']._options = None
  _globals['_ADDSERVICEDEPENDENCY'].fields_by_name['name']._serialized_options = b'\272H\006r\004\020\003\0302'
  _globals['_ADDSERVICEDEPENDENCY'].fields_by_name['application']._options = None
  _globals['_ADDSERVICEDEPENDENCY'].fields_by_name['application']._serialized_options = b'\272H\006r\004\020\003\0302'
  _globals['_ADDSERVICEDEPENDENCY'].fields_by_name['dependency_name']._options = None
  _globals['_ADDSERVICEDEPENDENCY'].fields_by_name['dependency_name']._serialized_options = b'\272H\006r\004\020\003\0302'
  _globals['_ADDSERVICEDEPENDENCY'].fields_by_name['dependency_application']._options = None
  _globals['_ADDSERVICEDEPENDENCY'].fields_by_name['dependency_application']._serialized_options = b'\272H\006r\004\020\003\0302'
  _globals['_ADDSERVICEDEPENDENCY'].fields_by_name['project_path']._options = None
  _globals['_ADDSERVICEDEPENDENCY'].fields_by_name['project_path']._serialized_options = b'\272H\004r\002\020\003'
  _globals['_ADDSERVICE']._serialized_start=115
  _globals['_ADDSERVICE']._serialized_end=360
  _globals['_SETSERVICEACTIVE']._serialized_start=363
  _globals['_SETSERVICEACTIVE']._serialized_end=555
  _globals['_ADDSERVICEDEPENDENCY']._serialized_start=558
  _globals['_ADDSERVICEDEPENDENCY']._serialized_end=868
# @@protoc_insertion_point(module_scope)
