# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/builder/v0/deployment.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from services.builder.v0 import docker_pb2 as services_dot_builder_dot_v0_dot_docker__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$services/builder/v0/deployment.proto\x12\x13services.builder.v0\x1a services/builder/v0/docker.proto\"|\n\nDeployment\x12\x1c\n\tnamespace\x18\x01 \x01(\tR\tnamespace\x12H\n\tkustomize\x18\x02 \x01(\x0b\x32(.services.builder.v0.KustomizeDeploymentH\x00R\tkustomizeB\x06\n\x04kind\"\x85\x01\n\x13KustomizeDeployment\x12L\n\rbuild_context\x18\x01 \x01(\x0b\x32\'.services.builder.v0.DockerBuildContextR\x0c\x62uildContext\x12 \n\x0b\x64\x65stination\x18\x02 \x01(\tR\x0b\x64\x65stination*\x1f\n\x0e\x44\x65ploymentKind\x12\r\n\tKUSTOMIZE\x10\x00\x42\xd6\x01\n\x17\x63om.services.builder.v0B\x0f\x44\x65ploymentProtoP\x01Z<github.com/codefly-dev/core/generated/go/services/builder/v0\xa2\x02\x03SBV\xaa\x02\x13Services.Builder.V0\xca\x02\x13Services\\Builder\\V0\xe2\x02\x1fServices\\Builder\\V0\\GPBMetadata\xea\x02\x15Services::Builder::V0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.builder.v0.deployment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.services.builder.v0B\017DeploymentProtoP\001Z<github.com/codefly-dev/core/generated/go/services/builder/v0\242\002\003SBV\252\002\023Services.Builder.V0\312\002\023Services\\Builder\\V0\342\002\037Services\\Builder\\V0\\GPBMetadata\352\002\025Services::Builder::V0'
  _globals['_DEPLOYMENTKIND']._serialized_start=357
  _globals['_DEPLOYMENTKIND']._serialized_end=388
  _globals['_DEPLOYMENT']._serialized_start=95
  _globals['_DEPLOYMENT']._serialized_end=219
  _globals['_KUSTOMIZEDEPLOYMENT']._serialized_start=222
  _globals['_KUSTOMIZEDEPLOYMENT']._serialized_end=355
# @@protoc_insertion_point(module_scope)
