apiVersion: batch/v1
kind: Job
metadata:
  name: store
  namespace: python-visitors-backend-localkube
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: store
          image: image:tag
          envFrom:
            - secretRef:
                name: secret-store
      restartPolicy: Never
