apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: python-visitors-backend-aws
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      name: http-port
      port: 8080
      targetPort: 8080
