# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: observability/v0/sessions.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fobservability/v0/sessions.proto\x12\x10observability.v0\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n\x0fProjectSnapshot\x12\x12\n\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\"z\n\x13\x41pplicationSnapshot\x12\x12\n\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12;\n\x07project\x18\x03 \x01(\x0b\x32!.observability.v0.ProjectSnapshotR\x07project\"\xc1\x01\n\x0fPartialSnapshot\x12\x12\n\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12;\n\x07project\x18\x03 \x01(\x0b\x32!.observability.v0.ProjectSnapshotR\x07project\x12I\n\x0c\x61pplications\x18\x04 \x03(\x0b\x32%.observability.v0.ApplicationSnapshotR\x0c\x61pplications\"\xde\x01\n\x07Session\x12\x12\n\x04uuid\x18\x01 \x01(\tR\x04uuid\x12*\n\x02\x61t\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x02\x61t\x12=\n\x07partial\x18\x03 \x01(\x0b\x32!.observability.v0.PartialSnapshotH\x00R\x07partial\x12I\n\x0b\x61pplication\x18\x04 \x01(\x0b\x32%.observability.v0.ApplicationSnapshotH\x00R\x0b\x61pplicationB\t\n\x07sessionB\xc1\x01\n\x14\x63om.observability.v0B\rSessionsProtoP\x01Z9github.com/codefly-dev/core/generated/go/observability/v0\xa2\x02\x03OVX\xaa\x02\x10Observability.V0\xca\x02\x10Observability\\V0\xe2\x02\x1cObservability\\V0\\GPBMetadata\xea\x02\x11Observability::V0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'observability.v0.sessions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.observability.v0B\rSessionsProtoP\001Z9github.com/codefly-dev/core/generated/go/observability/v0\242\002\003OVX\252\002\020Observability.V0\312\002\020Observability\\V0\342\002\034Observability\\V0\\GPBMetadata\352\002\021Observability::V0'
  _globals['_PROJECTSNAPSHOT']._serialized_start=86
  _globals['_PROJECTSNAPSHOT']._serialized_end=143
  _globals['_APPLICATIONSNAPSHOT']._serialized_start=145
  _globals['_APPLICATIONSNAPSHOT']._serialized_end=267
  _globals['_PARTIALSNAPSHOT']._serialized_start=270
  _globals['_PARTIALSNAPSHOT']._serialized_end=463
  _globals['_SESSION']._serialized_start=466
  _globals['_SESSION']._serialized_end=688
# @@protoc_insertion_point(module_scope)
